### PR TITLE
Update README about min k8s version

### PR DESCRIPTION
**Pull request by artursouza**
Fix for #20

### CODE REVIEW

**Comment by wonderflow** [comment]
Does it fix #20 ? I'm wondering if it possible to be compatible with k8s 1.16

**Comment by artursouza** [comment]
Yes, it fixes #20

**Comment by artursouza** [comment]
I tried with minikube and k8s 1.16 does not work as it fails to start provider-azure.

**Review by wonderflow — APPROVED** [review]
LGTM

**Comment by ryanzhang-oss** [comment]
> I tried with minikube and k8s 1.16 does not work as it fails to start provider-azure.

what error message do you see on 1.16?

**Pull request merged**
