### PR TITLE
Remove Helm chart NOTES.txt

### PR DESCRIPTION
**Pull request by negz**
Currently after installing the chart the following is printed:

```
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace crossplane-system -l "app.kubernetes.io/name=oam-core-resources,app.kubernetes.io/instance=addon-oam-kubernetes-local" -o jsonpath
="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace crossplane-system port-forward $POD_NAME 8080:80
```

As far as I can tell this is creating a proxy to the OAM controller container, which I don't think actually serves HTTP (apart from prometheus metrics). I'd like to remove these notes before we package this addon with Crossplane 0.11 as they seem a little misleading.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Well, at least we could add a line 'oam-local controller is deployed'

**Comment by negz** [comment]
> Well, at least we could add a line 'oam-local controller is deployed'

Is that common? In my experience Helm charts follow the unix pattern of "if you don't get an error, it worked."

**Comment by hongchaodeng** [comment]
I don't have any opinion on this.

Just share an example:
https://github.com/oam-dev/rudr/blob/master/charts/rudr/templates/NOTES.txt

```
Rudr is a Kubernetes controller to manage Configuration CRDs.

It has been successfully installed.
```

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Comment by negz** [comment]
Thanks @hongchaodeng!

**Pull request merged**
