### PR TITLE
Add README and manual steps for the e2e test

### PR DESCRIPTION
**Pull request by ryanzhang-oss**
Add the end to end instructions to run a complete OAM Kubernetes platform

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@ryanzhang-oss this is very helpful, thank you! We will be able to eliminate some of these steps when we add the packaging machinery (similar to what is done here: https://github.com/crossplane/addon-oam-kubernetes-remote/pull/2). Do you prefer to go ahead and merge this and then circle back with the packaging (which I can assist with)?

**Comment by hongchaodeng** [comment]
@hasheddan That sounds great!

**Review by hongchaodeng — APPROVED** [review]
LGTM

**Comment by ryanzhang-oss** [comment]
> @ryanzhang-oss this is very helpful, thank you! We will be able to eliminate some of these steps when we add the packaging machinery (similar to what is done here: [crossplane/addon-oam-kubernetes-remote#2](https://github.com/crossplane/addon-oam-kubernetes-remote/pull/2)). Do you prefer to go ahead and merge this and then circle back with the packaging (which I can assist with)?

To be honest, I don't understand what does the `packaging machinery` do in your PR.  I was thinking of adding a helm chart and be done with it.

**Pull request merged**
